name: flutter_app_dialog
description: I have been experimenting with flutter for a while and I stumbled a lot of times making custom widgets from designs for apps. Though flutter is incredibly easy to make UI components, you have to go through a lot of experimental processes to get what we want. In these packages, I want to create a simple dialog that can't help you save a lot of time and you can custom it.
version: 0.0.2
homepage: https://github.com/Nhattandev/flutter_app_dialog.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: