name: flutter_app_dialog
description: custom dialog
version: 0.0.1
homepage: https://github.com/Nhattandev/flutter_app_dialog.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: