name: flutter_app_dialog
description: Flutter app dialog is a simple package to build a dialog that you can save a lot of time.
version: 0.2.0
homepage: https://github.com/Nhattandev/flutter_app_dialog.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: